# Generated by Django 4.2 on 2023-04-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customername',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='tripname',
        ),
    ]
