# Generated by Django 4.2 on 2023-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_transactionitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='totalprice',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trip',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(blank=True, to='project.transactionitem'),
        ),
    ]
