# Generated by Django 4.2 on 2023-05-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
