# Generated by Django 4.2 on 2023-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
        migrations.AddField(
            model_name='trip',
            name='date_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
